### ISSUE TITLE
ng2 Datepicker dates displayed incorrectly

### ISSUE THREAD

**Issue by tejassawant54** [jkuri/ng2-datepicker#119]
Hello jkuri,

I am really impressed by the code and the work you have done for creating this datepicker. Recently I used the datepicker but I noticed that there is problem with this datepicker its not showing the correct calendar. You might want to look into this issue. 

![ng2_datepicker](https://cloud.githubusercontent.com/assets/8862628/21244406/16c777bc-c2e3-11e6-8a13-3e58bbf3be72.PNG)

**Comment by CK110** [comment]
i get the same problem，i think it's a bug ,but you can set the options.firstWeekdaySunday= true to solve it

**Comment by jkuri** [comment]
@tejassawant54 thanks for notice, I'll make a fix.

**Comment by tejassawant54** [comment]
@CK110 Thanks for replying i will try this
@jkuri No problem :)

**Comment by tejassawant54** [comment]
@jkuri I have a quick question can we change the format depending on the requirement by just passing an attribute to the ng2-datepicker component ?

**Comment by jkuri** [comment]
its hard coded at this moment, PRs welcome

**Comment by tejassawant54** [comment]
@jkuri  ok thanks ... sure :)

**Comment by tejassawant54** [comment]
Solution for viewFormat: 
Use:
<ng2-datepicker [(ngModel)]="date" [viewFormat]="DD-MM-YYYY" ></ng2-datepicker>

Default format set in datepicker-options.class.ts 
this.format = obj && obj.format ? obj.format : 'dddd MMMM DD, YYYY';

ng2-datepicker.component.ts
export class DatePickerComponent implements ControlValueAccessor, OnInit {

@Input() viewFormat: string;

Inside ngOnInit() {

    if( this.viewFormat){
      this.options.format = this.viewFormat || this.options.format;
    }
}

**Comment by jkuri** [comment]
Hi @tejassawant54, this should be resolved with https://github.com/jkuri/ng2-datepicker/commit/740f220f38d101e5dded52ac21a258a8a31ffd43. Can you please confirm?

**Comment by sbroways** [comment]
I'm still having the same issue with wrong dates. I also see the [Demo](http://ng2-datepicker.jankuri.com/) remains one day off. 
How are the options intended to be passed into the ng2-datepicker element? It says with property bind in the docs, so I'm not sure how to pass property + key + value? Something along these lines?:
`<ng2-datepicker id="date-picker" ngModel name="date" #date="ngModel" [options]="autoApply?.true"></ng2-datepicker>`
How would I pass style 'bold' which takes a string?

Thanks for the help and open-source contribution. The picker looks great.

**Comment by CK110** [comment]
@sbroways <ng2-datepicker id="date-picker" ngModel name="date" #date="ngModel" [options]="customoptions"></ng2-datepicker> , the customoptions is a variable， and you define this customotions in the ts class
like this：
```
export class A{

customoptions: DatePickerOptions;

ngOnInit(){
        this.customoptions =new DatePickerOptions({
            autoApply:true,
            style:'bold'
        })
}

} 
```

or you can just wirte in template ,like this:
```
<ng2-datepicker id="date-picker" ngModel name="date" #date="ngModel" [options]="{autoApply:true,style:'bold'}"></ng2-datepicker>
```

**Comment by sbroways** [comment]
@CK110 Worked brilliantly! Thank you! The option to set firstWeekSunday also aligned dates to day of week for me, so calendar is functioning properly now.

**Comment by lidiooliveira** [comment]
Thank you @sbroways and @CK110 it's work.
About the language, does it support pt-BR?

**Comment by CK110** [comment]
@lidiooliveira , you can just try DatePickerOptions.locale='pt-br' , and maybe you need import the pt-br.js or   locales.js

**Comment by killerengel** [comment]
@lidiooliveira  what I did was go to your project folder: node_modules\ng2-datepicker\src\components
In the file "ng2-datepicker.component.ts" you change what you want, "Select Year" I converted to "Selecionar Ano", 

div class="datepicker-calendar-day-names"
Change the names T S Q to or whatever: Dom. Seg. Ter. Qua. Quin.

div class="datepicker-buttons" *ngIf="!options.autoApply"
Change "Today" to "Hoje", "Apply" To "Confirmar"

After that, you must have Typescript installed "npm install -g typescript", then you type: on the PATH (ex.: C:\Users\USERNAME\Desktop\Projects\ProjectName\node_modules\ng2-datepicker\src\components) folder tsc ng2-datepicker.component.ts then it will compile and you just reboot the server, in my case ionic serve.

I hope that helps.

**Comment by lidiooliveira** [comment]
@killerengel Thanks a lot for the help.

**Comment by himajaM** [comment]
pls help me for my issue :: 

when i am submiting form, inserting the date by one day behind
i.e 2017-04-02  to 2017-04-01.

I am using ng2-datetime-picker by importing .

Below is my form input , how i am using datepicker ::
 <div class="input-group">
                <input type="text" class="form-control" name="SwitchDate" formControlName="SwitchDate" [value]="_job?.SwitchDate"
                    ng2-datetime-picker date-only="true" (ngModelChange)="changeValue($event,'JobAdditionalInfo','EntityTypeSwitchDate')" />
                <i class="fa fa-calendar"></i>
            </div>

thank you in advance.

**Comment by killerengel** [comment]
+himajaM
moment.utc(YourdateString).format('YYYY, MM, DD')
maybe the format above is not the same of yours, but 'utc' usually solve this problem.

**Comment by himajaM** [comment]
Any body can suggest me for my doubt please..!

Using ng2-datetime-picker, i want to disable  all dates before current date 
Below is my input tag how i am using datePicker : 

 <input type="text" class="form-control" name="SwitchDate" ng2-datetime-picker  date-only="true"  />

Thanks in Advance
