### ISSUE TITLE
clear a date?

### ISSUE THREAD

**Issue by dixitk13** [jkuri/ng2-datepicker#171]
@jkuri 
 <ng2-datepicker [(ngModel)]="end_date"></ng2-datepicker>

how does one clear the date after it has been selected via Apply button?

**Comment by uncarlo** [comment]
Did you ever find out how to do it?

**Comment by dixitk13** [comment]
I did get thro' with a incomplete solution which was ugly, so I switched over to md-input-container. But you can try something like 

```
end_date.date = new DateModel();
```

**Comment by uncarlo** [comment]
Yeah I did that too. I just want to make sure that the previous DateModel object gets disposed of correctly, but I'll take make sure of that later. Thank you!

**Comment by jkuri** [comment]
this is now resolved with "clear" button in the ui. please check `1.6.0` version. thanks.

**Comment by zjx** [comment]
@jkuri, is the clear function still exist in the latest version? i try nom install the latest version seems there is no clear button..

**Comment by luckynipun** [comment]
@jkuri, the clear button does not exist on the new version?
![image](https://user-images.githubusercontent.com/17171812/34349106-127ddd02-ea35-11e7-898e-47f4d67c1566.png)

**Comment by andrebrz** [comment]
> this is now resolved with "clear" button in the ui. please check `1.6.0` version. thanks.

I'm using ^3.1.1 version... How can I use this "clear" button?
